- name: Install Pip
  become: true
  apt:
    name: python-pip
    state: latest


- name: upgrade pip
  shell: pip install --upgrade pip

- name: Install python-pkg
  become: true
  apt:
    name: python-pkg-resources
    state: latest

- name: Install aptitude
  become: true
  apt:
    name: aptitude

- name: Install setuptools
  become: true
  apt:
    name: python-setuptools
    state: latest

- name: Install required packages on all hosts
  apt: name={{item}} state=installed
  with_items:
    - ntp
    - ntpdate
    - python-pip
    - python-selinux
    - python-dev
    - libffi-dev
    - libssl-dev
    - gcc
    - git

- name: mount /run
  command: "mount --make-shared /run"
